### ISSUE TITLE
0.9.3 project imported into Eclipse yields many errors

### ISSUE THREAD

**Issue by mindonly** [phelps-sg/jabm#2] opened 2016-09-10 00:46 UTC
Hi,

I've tried importing the 0.9.3 zip project into Eclipse as suggested on the Sourceforge page, but with little luck.  Both Eclipse 3.8 (Juno) on Linux and 4.6 (Neon) on OSX present many "X cannot be resolved to a type" errors all over the code.  Based on a brief examination it appears that the `pom.xml` file might be mis-specified, and thereby the various dependencies aren't handled properly.

I was wondering if someone with better knowledge of the code could possibly try to reproduce this behavior, and perhaps suggest a solution?

For what it's worth, I **was** able to import the 0.8_01 zip project successfully into Eclipse, as suggested by the lab exercise sheet [found here](http://jabm.sourceforge.net/doc/easss2013/EASSS_lab_elfarolbar.pdf).  However, I'd like to work with the latest version of the code if possible.

In addition, it seems the latest 0.9.3 updates are not on github yet, will that change?

Thanks!

**Comment by phelps-sg** [comment] 2016-09-10 09:56
On 10/09/16 01:46, mindonly wrote:

> Hi,
>
> I've tried importing the 0.9.3 zip project into Eclipse as suggested 
> on the Sourceforge page, but with little luck. Both Eclipse 3.8 (Juno) 
> on Linux and 4.6 (Neon) on OSX present many "X cannot be resolved to a 
> type" errors all over the code. Based on a brief examination it 
> appears that the |pom.xml| file might be mis-specified, and thereby 
> the various dependencies aren't handled properly.
>
> I was wondering if someone with better knowledge of the code could 
> possibly try to reproduce this behavior, and perhaps suggest a solution?
>

I am unable to reproduce this with Eclipse 4.6 on Linux.

It sounds as if for some reason the Eclipse Maven plugin was unable to 
download and link the dependencies when you imported the project.  This 
could be caused e.g. by a problem with your internet connection at the 
time of the import.

Have you tried updating the Maven dependencies?  You can do this by 
right-clicking on the jabm project in the Project Explorer, then Choose 
'Maven/Update Project'.

> In addition, it seems the latest 0.9.3 updates are not on github yet, 
> will that change?
>

In theory, the github repo should be ahead of the 0.9.3 release. Could 
you be more specific?  What is the exact discrepancy?

**Comment by mindonly** [comment] 2016-09-12 22:12
Hi, thanks for your response.  The reason I wondered about the code on Github is because the date on the 0.9.3 zip download from Sourceforge doesn't seem to match the date of the last Github source commit, but maybe I'm missing something or just looking at it wrong.

Anyway, I've tried this on a third computer, Windows this time, and I get the same result.  So I guess I'm having a tough time understanding what I'm doing wrong if the root cause of the issue is on my end.

I went back and uninstalled Eclipse 4.6 on OSX and reinstalled it.  I re-downloaded the 'jabm-with-examples-0.9.3-project.zip' from Sourceforge and imported the project with the File - Import - Existing Projects into Workspace option.  I tried the Maven/Update Project option you suggested but the result is the same, there are 1329 errors, mainly of the "X cannot be resolved to a type" variety.  I've attached screenshots of what I see immediately after installation.  

The POM error is as follows:

`Project build error: Non-resolvable parent POM for net.sourceforge.jabm:jabm-examples:[unknown-version]: Failure to find net.sourceforge.jabm:jabm-with-examples:pom:0.9.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM`

![screen shot 2016-09-12 at 17 55 15](https://cloud.githubusercontent.com/assets/17532588/18454436/5ba32306-7912-11e6-9b11-87677ff21dbd.png)

![screen shot 2016-09-12 at 17 57 56](https://cloud.githubusercontent.com/assets/17532588/18454452/7b68ac38-7912-11e6-9893-f626ef92cdf8.png)

I appreciate your time, thanks for your help.

**Comment by phelps-sg** [comment] 2016-09-13 08:36
ok, the exact Maven error helps :-).

To resolve this problem you can add the following snippet to the `pom.xml` file in both the `jabm` and `jabm-examples` projects:

~~~xml
<repositories>
	<repository>
		<id>jabm.sourceforge.net</id>
		<url>http://jabm.sourceforge.net/mvn-repo/jabm</url>
	</repository>
 </repositories>
~~~ 

Once you have made change to the pom.xml files, select each project and choose Maven/Update Project.

I will push this to the git repo, and the change will be incorporated in the next release, but in the mean-time the easiest thing is probably to apply the fix directly.

HTH,
Steve.

**Closed** 2019-12-20 13:56 UTC
